server:
  port: 9082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/base?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: zqbxcmj
  resources:
    static-locations : classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/static/page/,classpath:/templates/
#配置mybatis
mybatis:
  #扫描mapper 文件路径
  #com.javaoffers.batis.modelhelper.mapper-locations : classpath*:com/mh/others/spring_/**/*.xml
  mapper-locations : classpath*:static/**/**.xml
  configuration:
    #sql打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# mybatis-jql 配置
mybatis-jql:
  # 慢sql超过10毫秒打印慢sql
  slow-sql:
    time : 10